export const
  apiKey = 'd774965552f6cdae29a22bec30d6bb92',
  locationNumLimit: number = 1,
  owner = 'music-soul1-1',
  repoName = 'weather-app',
  langs = [
    { label: 'Afrikaans', value: 'af' },
    { label: 'Albanian', value: 'al' },
    { label: 'Arabic', value: 'ar' },
    { label: 'Azerbaijani', value: 'az' },
    { label: 'Bulgarian', value: 'bg' },
    { label: 'Catalan', value: 'ca' },
    { label: 'Czech', value: 'cz' },
    { label: 'Danish', value: 'da' },
    { label: 'German', value: 'de' },
    { label: 'Greek', value: 'el' },
    { label: 'English', value: 'en' },
    { label: 'Basque', value: 'eu' },
    { label: 'Persian (Farsi)', value: 'fa' },
    { label: 'Finnish', value: 'fi' },
    { label: 'French', value: 'fr' },
    { label: 'Galician', value: 'gl' },
    { label: 'Hebrew', value: 'he' },
    { label: 'Hindi', value: 'hi' },
    { label: 'Croatian', value: 'hr' },
    { label: 'Hungarian', value: 'hu' },
    { label: 'Indonesian', value: 'id' },
    { label: 'Italian', value: 'it' },
    { label: 'Japanese', value: 'ja' },
    { label: 'Korean', value: 'kr' },
    { label: 'Latvian', value: 'la' },
    { label: 'Lithuanian', value: 'lt' },
    { label: 'Macedonian', value: 'mk' },
    { label: 'Norwegian', value: 'no' },
    { label: 'Dutch', value: 'nl' },
    { label: 'Polish', value: 'pl' },
    { label: 'Portuguese', value: 'pt' },
    { label: 'Português Brasil', value: 'pt_br' },
    { label: 'Romanian', value: 'ro' },
    { label: 'Russian', value: 'ru' },
    { label: 'Swedish', value: 'sv' },
    { label: 'Slovak', value: 'sk' },
    { label: 'Slovenian', value: 'sl' },
    { label: 'Spanish', value: 'es' },
    { label: 'Serbian', value: 'sr' },
    { label: 'Thai', value: 'th' },
    { label: 'Turkish', value: 'tr' },
    { label: 'Ukrainian', value: 'ua' },
    { label: 'Vietnamese', value: 'vi' },
    { label: 'Chinese Simplified', value: 'zh_cn' },
    { label: 'Chinese Traditional', value: 'zh_tw' },
    { label: 'Zulu', value: 'zu' },
  ],
  units = [
    {label: 'Metric', value: 'metric'},
    {label: 'Imperial', value: 'imperial'}
  ],
  timestamps = [
    { label: '3', value: '3' },
    { label: '4', value: '4' },
    { label: '5', value: '5' },
    { label: '6', value: '6' },
    { label: '7', value: '7' },
    { label: '8', value: '8' },
    { label: '9', value: '9' },
    { label: '10', value: '10' },
    { label: '11', value: '11' },
    { label: '12', value: '12' },
    { label: '13', value: '13' },
    { label: '14', value: '14' },
    { label: '15', value: '15' },
    { label: '16', value: '16' },
    { label: '17', value: '17' },
    { label: '18', value: '18' },
    { label: '19', value: '19' },
    { label: '20', value: '20' },
    { label: '21', value: '21' },
    { label: '22', value: '22' },
    { label: '23', value: '23' },
    { label: '24', value: '24' },
    { label: '25', value: '25' },
    { label: '26', value: '26' },
    { label: '27', value: '27' },
    { label: '28', value: '28' },
    { label: '29', value: '29' },
    { label: '30', value: '30' },
    { label: '31', value: '31' },
    { label: '32', value: '32' },
    { label: '33', value: '33' },
    { label: '34', value: '34' },
    { label: '35', value: '35' },
    { label: '36', value: '36' },
    { label: '37', value: '37' },
    { label: '38', value: '38' },
    { label: '39', value: '39' },
    { label: '40', value: '40' },
  ],
  measuringUnits = {
    metric: {
      temp: '°C',
      speed: 'm/s',
    },
    imperial: {
      temp: '°F',
      speed: 'mi/h',
    }
  };